TRAIN_DATA_PATH = "scr/model/train.csv"

MODEL_WEIGHTS_PATH = "scr/model/weights.pkl"

LEARNING_RATE = 0.10
NUM_ITERATIONS = 500
DEV_SET_SIZE = 1000

INPUT_SIZE = 784
HIDDEN_SIZE = 50
NUM_CLASSES = 10